
domain: g14n.info

permalink: ./:year/:month/:title/

gems:
  - jekyll-sitemap

markdown: kramdown

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

# Custom vars

google-analytics:
  id: UA-12635045-12

